os: linux
dist: bionic
language: python
python:
    - "3.8.5"
install:
    - pip install -r requirements.txt
script:
    - coverage run psction/manage.py test prescription
after_success:
    - coverage report
